/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PageantryRouteImport } from './routes/pageantry'
import { Route as ModelingRouteImport } from './routes/modeling'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VoteCallbackRouteImport } from './routes/vote.callback'
import { Route as VoteIdRouteImport } from './routes/vote.$id'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as RegisterCallbackRouteImport } from './routes/register.callback'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminContestantsRouteImport } from './routes/admin.contestants'
import { Route as ApiPublicPageantSplatRouteImport } from './routes/api/public/pageant.$'

const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PageantryRoute = PageantryRouteImport.update({
  id: '/pageantry',
  path: '/pageantry',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelingRoute = ModelingRouteImport.update({
  id: '/modeling',
  path: '/modeling',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VoteCallbackRoute = VoteCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => VoteRoute,
} as any)
const VoteIdRoute = VoteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VoteRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCallbackRoute = RegisterCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => RegisterRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestantsRoute = AdminContestantsRouteImport.update({
  id: '/contestants',
  path: '/contestants',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPageantSplatRoute = ApiPublicPageantSplatRouteImport.update({
  id: '/api/public/pageant/$',
  path: '/api/public/pageant/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/magazine': typeof MagazineRoute
  '/modeling': typeof ModelingRoute
  '/pageantry': typeof PageantryRoute
  '/register': typeof RegisterRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/vote': typeof VoteRouteWithChildren
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/register/callback': typeof RegisterCallbackRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/vote/$id': typeof VoteIdRoute
  '/vote/callback': typeof VoteCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/pageant/$': typeof ApiPublicPageantSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/magazine': typeof MagazineRoute
  '/modeling': typeof ModelingRoute
  '/pageantry': typeof PageantryRoute
  '/register': typeof RegisterRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/vote': typeof VoteRouteWithChildren
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/register/callback': typeof RegisterCallbackRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/vote/$id': typeof VoteIdRoute
  '/vote/callback': typeof VoteCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/pageant/$': typeof ApiPublicPageantSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/magazine': typeof MagazineRoute
  '/modeling': typeof ModelingRoute
  '/pageantry': typeof PageantryRoute
  '/register': typeof RegisterRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/vote': typeof VoteRouteWithChildren
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/register/callback': typeof RegisterCallbackRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/vote/$id': typeof VoteIdRoute
  '/vote/callback': typeof VoteCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/pageant/$': typeof ApiPublicPageantSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/magazine'
    | '/modeling'
    | '/pageantry'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/vote'
    | '/admin/contestants'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/category/$slug'
    | '/register/callback'
    | '/stories/$slug'
    | '/vote/$id'
    | '/vote/callback'
    | '/admin/'
    | '/api/public/pageant/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/magazine'
    | '/modeling'
    | '/pageantry'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/vote'
    | '/admin/contestants'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/category/$slug'
    | '/register/callback'
    | '/stories/$slug'
    | '/vote/$id'
    | '/vote/callback'
    | '/admin'
    | '/api/public/pageant/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/magazine'
    | '/modeling'
    | '/pageantry'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/vote'
    | '/admin/contestants'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/category/$slug'
    | '/register/callback'
    | '/stories/$slug'
    | '/vote/$id'
    | '/vote/callback'
    | '/admin/'
    | '/api/public/pageant/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  MagazineRoute: typeof MagazineRoute
  ModelingRoute: typeof ModelingRoute
  PageantryRoute: typeof PageantryRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  VoteRoute: typeof VoteRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  ApiPublicPageantSplatRoute: typeof ApiPublicPageantSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pageantry': {
      id: '/pageantry'
      path: '/pageantry'
      fullPath: '/pageantry'
      preLoaderRoute: typeof PageantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modeling': {
      id: '/modeling'
      path: '/modeling'
      fullPath: '/modeling'
      preLoaderRoute: typeof ModelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vote/callback': {
      id: '/vote/callback'
      path: '/callback'
      fullPath: '/vote/callback'
      preLoaderRoute: typeof VoteCallbackRouteImport
      parentRoute: typeof VoteRoute
    }
    '/vote/$id': {
      id: '/vote/$id'
      path: '/$id'
      fullPath: '/vote/$id'
      preLoaderRoute: typeof VoteIdRouteImport
      parentRoute: typeof VoteRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/callback': {
      id: '/register/callback'
      path: '/callback'
      fullPath: '/register/callback'
      preLoaderRoute: typeof RegisterCallbackRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contestants': {
      id: '/admin/contestants'
      path: '/contestants'
      fullPath: '/admin/contestants'
      preLoaderRoute: typeof AdminContestantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/pageant/$': {
      id: '/api/public/pageant/$'
      path: '/api/public/pageant/$'
      fullPath: '/api/public/pageant/$'
      preLoaderRoute: typeof ApiPublicPageantSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminContestantsRoute: typeof AdminContestantsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContestantsRoute: AdminContestantsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RegisterRouteChildren {
  RegisterCallbackRoute: typeof RegisterCallbackRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterCallbackRoute: RegisterCallbackRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface VoteRouteChildren {
  VoteIdRoute: typeof VoteIdRoute
  VoteCallbackRoute: typeof VoteCallbackRoute
}

const VoteRouteChildren: VoteRouteChildren = {
  VoteIdRoute: VoteIdRoute,
  VoteCallbackRoute: VoteCallbackRoute,
}

const VoteRouteWithChildren = VoteRoute._addFileChildren(VoteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  MagazineRoute: MagazineRoute,
  ModelingRoute: ModelingRoute,
  PageantryRoute: PageantryRoute,
  RegisterRoute: RegisterRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  VoteRoute: VoteRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  ApiPublicPageantSplatRoute: ApiPublicPageantSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
